drop TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO (ID INT, NOMBRE VARCHAR(10), APELLIDO VARCHAR(10), PRIMARY KEY(ID)); 
INSERT INTO USUARIO (ID,NOMBRE,APELLIDO) VALUES (0,'James','Bond');
DISCONNECT;