/*
 * This file is generated by jOOQ.
 */
package comun.jooq;


import comun.jooq.tables.Usuario;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SYS_IDX_SYS_PK_10091_10092 = Indexes0.SYS_IDX_SYS_PK_10091_10092;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index SYS_IDX_SYS_PK_10091_10092 = Internal.createIndex("SYS_IDX_SYS_PK_10091_10092", Usuario.USUARIO, new OrderField[] { Usuario.USUARIO.ID }, true);
    }
}
