/*
 * This file is generated by jOOQ.
 */
package comun.jooq;


import comun.jooq.tables.Usuario;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.USUARIO</code>.
     */
    public static final Usuario USUARIO = Usuario.USUARIO;
}
